// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.1
// source: washstation.proto

package washstationpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NewWashPackageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string  `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Category  uint32  `protobuf:"varint,2,opt,name=category,proto3" json:"category,omitempty"` // cc motorbike
	Price     float32 `protobuf:"fixed32,3,opt,name=price,proto3" json:"price,omitempty"`
	CreatedBy uint32  `protobuf:"varint,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"` // admin_id
}

func (x *NewWashPackageData) Reset() {
	*x = NewWashPackageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_washstation_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NewWashPackageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NewWashPackageData) ProtoMessage() {}

func (x *NewWashPackageData) ProtoReflect() protoreflect.Message {
	mi := &file_washstation_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NewWashPackageData.ProtoReflect.Descriptor instead.
func (*NewWashPackageData) Descriptor() ([]byte, []int) {
	return file_washstation_proto_rawDescGZIP(), []int{0}
}

func (x *NewWashPackageData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NewWashPackageData) GetCategory() uint32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *NewWashPackageData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *NewWashPackageData) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

type CreateWashPackageResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt string `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
}

func (x *CreateWashPackageResponse) Reset() {
	*x = CreateWashPackageResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_washstation_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateWashPackageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWashPackageResponse) ProtoMessage() {}

func (x *CreateWashPackageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_washstation_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWashPackageResponse.ProtoReflect.Descriptor instead.
func (*CreateWashPackageResponse) Descriptor() ([]byte, []int) {
	return file_washstation_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWashPackageResponse) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CreateWashPackageResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type WashPackageCompactRepeated struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WashPackages []*WashPackageCompact `protobuf:"bytes,1,rep,name=wash_packages,json=washPackages,proto3" json:"wash_packages,omitempty"`
}

func (x *WashPackageCompactRepeated) Reset() {
	*x = WashPackageCompactRepeated{}
	if protoimpl.UnsafeEnabled {
		mi := &file_washstation_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WashPackageCompactRepeated) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WashPackageCompactRepeated) ProtoMessage() {}

func (x *WashPackageCompactRepeated) ProtoReflect() protoreflect.Message {
	mi := &file_washstation_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WashPackageCompactRepeated.ProtoReflect.Descriptor instead.
func (*WashPackageCompactRepeated) Descriptor() ([]byte, []int) {
	return file_washstation_proto_rawDescGZIP(), []int{2}
}

func (x *WashPackageCompactRepeated) GetWashPackages() []*WashPackageCompact {
	if x != nil {
		return x.WashPackages
	}
	return nil
}

type WashPackageCompact struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category uint32  `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Price    float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *WashPackageCompact) Reset() {
	*x = WashPackageCompact{}
	if protoimpl.UnsafeEnabled {
		mi := &file_washstation_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WashPackageCompact) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WashPackageCompact) ProtoMessage() {}

func (x *WashPackageCompact) ProtoReflect() protoreflect.Message {
	mi := &file_washstation_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WashPackageCompact.ProtoReflect.Descriptor instead.
func (*WashPackageCompact) Descriptor() ([]byte, []int) {
	return file_washstation_proto_rawDescGZIP(), []int{3}
}

func (x *WashPackageCompact) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WashPackageCompact) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WashPackageCompact) GetCategory() uint32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *WashPackageCompact) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type WashPackageID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id uint32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *WashPackageID) Reset() {
	*x = WashPackageID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_washstation_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WashPackageID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WashPackageID) ProtoMessage() {}

func (x *WashPackageID) ProtoReflect() protoreflect.Message {
	mi := &file_washstation_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WashPackageID.ProtoReflect.Descriptor instead.
func (*WashPackageID) Descriptor() ([]byte, []int) {
	return file_washstation_proto_rawDescGZIP(), []int{4}
}

func (x *WashPackageID) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type WashPackageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id       uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name     string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category uint32  `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Price    float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *WashPackageData) Reset() {
	*x = WashPackageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_washstation_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WashPackageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WashPackageData) ProtoMessage() {}

func (x *WashPackageData) ProtoReflect() protoreflect.Message {
	mi := &file_washstation_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WashPackageData.ProtoReflect.Descriptor instead.
func (*WashPackageData) Descriptor() ([]byte, []int) {
	return file_washstation_proto_rawDescGZIP(), []int{5}
}

func (x *WashPackageData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *WashPackageData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WashPackageData) GetCategory() uint32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *WashPackageData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

type UpdateWashPackageData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        uint32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string  `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Category  uint32  `protobuf:"varint,3,opt,name=category,proto3" json:"category,omitempty"`
	Price     float32 `protobuf:"fixed32,4,opt,name=price,proto3" json:"price,omitempty"`
	CreatedBy uint32  `protobuf:"varint,5,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
}

func (x *UpdateWashPackageData) Reset() {
	*x = UpdateWashPackageData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_washstation_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateWashPackageData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWashPackageData) ProtoMessage() {}

func (x *UpdateWashPackageData) ProtoReflect() protoreflect.Message {
	mi := &file_washstation_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWashPackageData.ProtoReflect.Descriptor instead.
func (*UpdateWashPackageData) Descriptor() ([]byte, []int) {
	return file_washstation_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateWashPackageData) GetId() uint32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateWashPackageData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateWashPackageData) GetCategory() uint32 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *UpdateWashPackageData) GetPrice() float32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateWashPackageData) GetCreatedBy() uint32 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

var File_washstation_proto protoreflect.FileDescriptor

var file_washstation_proto_rawDesc = []byte{
	0x0a, 0x11, 0x77, 0x61, 0x73, 0x68, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x77, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x79,
	0x0a, 0x12, 0x4e, 0x65, 0x77, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x44, 0x61, 0x74, 0x61, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65,
	0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x09,
	0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x22, 0x4a, 0x0a, 0x19, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x5f, 0x61, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x63, 0x0a, 0x1a, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x52, 0x65, 0x70, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x12, 0x45, 0x0a, 0x0d, 0x77, 0x61, 0x73, 0x68, 0x5f, 0x70, 0x61, 0x63, 0x6b,
	0x61, 0x67, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e, 0x77, 0x61, 0x73,
	0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74, 0x52, 0x0c, 0x77, 0x61,
	0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x22, 0x6a, 0x0a, 0x12, 0x57, 0x61,
	0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x22, 0x67, 0x0a, 0x0f, 0x57, 0x61, 0x73, 0x68, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x8c, 0x01, 0x0a, 0x15, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x61, 0x73, 0x68, 0x50,
	0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x42, 0x79, 0x32,
	0xb5, 0x03, 0x0a, 0x0b, 0x57, 0x61, 0x73, 0x68, 0x53, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x5e, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63,
	0x6b, 0x61, 0x67, 0x65, 0x12, 0x20, 0x2e, 0x77, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x65, 0x77, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x27, 0x2e, 0x77, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x57, 0x61, 0x73, 0x68,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x57, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64, 0x41, 0x6c, 0x6c, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61,
	0x63, 0x6b, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x1a, 0x28,
	0x2e, 0x77, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x61,
	0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x6d, 0x70, 0x61, 0x63, 0x74,
	0x52, 0x65, 0x70, 0x65, 0x61, 0x74, 0x65, 0x64, 0x12, 0x51, 0x0a, 0x13, 0x46, 0x69, 0x6e, 0x64,
	0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x42, 0x79, 0x49, 0x44, 0x12,
	0x1b, 0x2e, 0x77, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57,
	0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x44, 0x1a, 0x1d, 0x2e, 0x77,
	0x61, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x57, 0x61, 0x73, 0x68,
	0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x44, 0x61, 0x74, 0x61, 0x12, 0x50, 0x0a, 0x11, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65,
	0x12, 0x23, 0x2e, 0x77, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67,
	0x65, 0x44, 0x61, 0x74, 0x61, 0x1a, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x12, 0x48, 0x0a,
	0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61,
	0x67, 0x65, 0x12, 0x1b, 0x2e, 0x77, 0x61, 0x73, 0x68, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x57, 0x61, 0x73, 0x68, 0x50, 0x61, 0x63, 0x6b, 0x61, 0x67, 0x65, 0x49, 0x44, 0x1a,
	0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x45, 0x6d, 0x70, 0x74, 0x79, 0x42, 0x13, 0x5a, 0x11, 0x2f, 0x70, 0x62, 0x2f, 0x77,
	0x61, 0x73, 0x68, 0x73, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_washstation_proto_rawDescOnce sync.Once
	file_washstation_proto_rawDescData = file_washstation_proto_rawDesc
)

func file_washstation_proto_rawDescGZIP() []byte {
	file_washstation_proto_rawDescOnce.Do(func() {
		file_washstation_proto_rawDescData = protoimpl.X.CompressGZIP(file_washstation_proto_rawDescData)
	})
	return file_washstation_proto_rawDescData
}

var file_washstation_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_washstation_proto_goTypes = []any{
	(*NewWashPackageData)(nil),         // 0: wash_station.NewWashPackageData
	(*CreateWashPackageResponse)(nil),  // 1: wash_station.CreateWashPackageResponse
	(*WashPackageCompactRepeated)(nil), // 2: wash_station.WashPackageCompactRepeated
	(*WashPackageCompact)(nil),         // 3: wash_station.WashPackageCompact
	(*WashPackageID)(nil),              // 4: wash_station.WashPackageID
	(*WashPackageData)(nil),            // 5: wash_station.WashPackageData
	(*UpdateWashPackageData)(nil),      // 6: wash_station.UpdateWashPackageData
	(*emptypb.Empty)(nil),              // 7: google.protobuf.Empty
}
var file_washstation_proto_depIdxs = []int32{
	3, // 0: wash_station.WashPackageCompactRepeated.wash_packages:type_name -> wash_station.WashPackageCompact
	0, // 1: wash_station.WashStation.CreateWashPackage:input_type -> wash_station.NewWashPackageData
	7, // 2: wash_station.WashStation.FindAllWashPackages:input_type -> google.protobuf.Empty
	4, // 3: wash_station.WashStation.FindWashPackageByID:input_type -> wash_station.WashPackageID
	6, // 4: wash_station.WashStation.UpdateWashPackage:input_type -> wash_station.UpdateWashPackageData
	4, // 5: wash_station.WashStation.DeleteWashPackage:input_type -> wash_station.WashPackageID
	1, // 6: wash_station.WashStation.CreateWashPackage:output_type -> wash_station.CreateWashPackageResponse
	2, // 7: wash_station.WashStation.FindAllWashPackages:output_type -> wash_station.WashPackageCompactRepeated
	5, // 8: wash_station.WashStation.FindWashPackageByID:output_type -> wash_station.WashPackageData
	7, // 9: wash_station.WashStation.UpdateWashPackage:output_type -> google.protobuf.Empty
	7, // 10: wash_station.WashStation.DeleteWashPackage:output_type -> google.protobuf.Empty
	6, // [6:11] is the sub-list for method output_type
	1, // [1:6] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_washstation_proto_init() }
func file_washstation_proto_init() {
	if File_washstation_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_washstation_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*NewWashPackageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_washstation_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*CreateWashPackageResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_washstation_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*WashPackageCompactRepeated); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_washstation_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*WashPackageCompact); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_washstation_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*WashPackageID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_washstation_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*WashPackageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_washstation_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*UpdateWashPackageData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_washstation_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_washstation_proto_goTypes,
		DependencyIndexes: file_washstation_proto_depIdxs,
		MessageInfos:      file_washstation_proto_msgTypes,
	}.Build()
	File_washstation_proto = out.File
	file_washstation_proto_rawDesc = nil
	file_washstation_proto_goTypes = nil
	file_washstation_proto_depIdxs = nil
}
